# Generated by Django 3.2.8 on 2021-10-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='Notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
