# Generated by Django 3.2.8 on 2021-10-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211021_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('CSN221', 'CSN221'), ('CSN291', 'CSN291'), ('PHN005', 'PHN005')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY')], default='10:00-11:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(choices=[('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00')], default='MONDAY', max_length=20),
        ),
    ]
