# Generated by Django 3.2.8 on 2021-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211021_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='teaching_course',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('CSN221', 'CSN221'), ('CSN291', 'CSN291'), ('PHN005', 'PHN005'), ('MAN005', 'MAN005'), ('CEN105', 'CEN105')], default='1', max_length=10),
        ),
    ]
