# Generated by Django 3.2.8 on 2021-10-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211022_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY')], default='MONDAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(choices=[('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00')], default='10:00-11:00', max_length=20),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answered_status', models.BooleanField(default=False)),
                ('send_status', models.IntegerField()),
                ('from_prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.professor')),
                ('from_stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
                ('to_adm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.admin')),
                ('to_course', models.ManyToManyField(to='home.Course')),
            ],
        ),
    ]
