# Generated by Django 3.2.8 on 2021-10-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211024_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
