# Generated by Django 3.2.8 on 2021-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_query_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
