# Generated by Django 3.2.8 on 2021-10-27 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_query_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absentdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_of_absent', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_classes_count', models.IntegerField(blank=True, null=True)),
                ('total_classes_count', models.IntegerField(blank=True, null=True)),
                ('attendance_taking_status', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('absentdates', models.ManyToManyField(to='home.Absentdates')),
                ('cour', models.ManyToManyField(to='home.Course')),
                ('stud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
