# Generated by Django 3.2.8 on 2021-10-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_absentdates_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='limits',
            field=models.IntegerField(default=2),
        ),
    ]
