# Generated by Django 3.2.8 on 2021-10-28 16:46

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211027_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwordchangerid', models.IntegerField(blank=True, null=True)),
                ('passwordchangerotp', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='profprofilepic',
            field=models.FileField(blank=True, null=True, upload_to=home.models.faculty_directory_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='studprofilepic',
            field=models.FileField(blank=True, null=True, upload_to=home.models.student_directory_path),
        ),
    ]
