# Generated by Django 3.2.8 on 2021-10-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211028_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentdates',
            name='no_of_classes_absent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
