# Generated by Django 3.2.8 on 2021-10-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_absentdates_no_of_classes_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentdates',
            name='attendanceid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
