# Generated by Django 3.2.8 on 2021-10-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_absentdates_dates_of_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='spamprofilepic',
            field=models.FileField(blank=True, null=True, upload_to='spam_faculty_images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='spamprofilepic',
            field=models.FileField(blank=True, null=True, upload_to='spam_student_images/'),
        ),
    ]
